### ISSUE TITLE
Could I run paracel program outside `PARACEL_HOME`?

### ISSUE THREAD

**Issue by xunzhang** [douban/paracel#15]
In current version, I can only run paracel program in `PARACEL_HOME` with `prun.py`.

If I run outside, there are some linkage problems. Can I run paracel anywhere outside `PARACEL_HOME`?

**Comment by xunzhang** [comment]
See this pull request https://github.com/douban/paracel/pull/16 for the improvement. thanks.

**Comment by windreamer** [comment]
`LD_LIBRARY_PATH` is a bit too hacky, I think.

**Comment by xunzhang** [comment]
Related pull request https://github.com/douban/paracel/pull/16 started a discussion of whether setting linking option inside `prun.py` or not. I will write it down here. 

Some reviewer suggests that linking option of paracel is not related to the logic of framework itself. It is user's responsibility to handle that.

I agree with that and have already modified the original commit. A typical scene for an Internet company is that the system administrator installs paracel in its cluster and sets linking option correctly. A script user or developer does not need to care about it. This makes sense.

Consequently, there are usually two choices for personal users to set up linking option before running paracel programs:
1. Add your linking path(`PARACEL_INSTALL_PREFIX/lib`) into `/etc/ld.so.conf`(recommended)
2. Set `LD_LIBRARY_PATH` or `DYLD_LIBRARY_PATH` varible with `PARACEL_INSTALL_PREFIX/lib`.

**Comment by xunzhang** [comment]
Resolved
