### ISSUE TITLE
eigen  这个怎么安装呢?  Searching 9842 files for "Eigen_CHECK_FINE"  0 matches

### ISSUE THREAD

**Issue by joostshao** [douban/paracel#4]
没找到,我用的是最新版本的3.2.4,

求指教

**Comment by xunzhang** [comment]
@joostshao 问下你是在什么环境，能把详细的报错信息粘一下么？

**Comment by joostshao** [comment]
ubuntu 14.04 , 

错误信息如下:

➜  build git:(master) ✗ pwd
/home/ubuntu/paracel/build
➜  build git:(master) ✗ cmake -DCMAKE_BUILD_TYPE=Release ..
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   regex
--   filesystem
--   system
--   unit_test_framework
-- Find Eigen include path: /usr/local/include
-- Eigen check: 
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Eigen (missing: Eigen_CHECK_FINE)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmakes/FindEigen.cmake:30 (find_package_handle_standard_args)
  CMakeLists.txt:57 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/paracel/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/paracel/CMakeFiles/CMakeError.log".

**Comment by xunzhang** [comment]
我试了eigen3.2.4，并没有出现你说的问题。请尝试编译如下代码看能否正常运行，或者报什么错：

```cpp
// test.cc
#include <eigen3/Eigen/Dense>
#include <eigen3/Eigen/Sparse>

int main(int argc, char *argv[]) {
    Eigen::VectorXd tmp(7);
    return 0;
}
```

**Comment by mckelvin** [comment]
之前我写 .travis.yml 的时候也遇到过这个问题，可能和Eigen版本 < 3.1.0有关。 @joostshao 的 `/home/ubuntu/paracel/CMakeFiles/CMakeError.log` 会有详细的报错信息。

**Comment by xunzhang** [comment]
@mckelvin 他说他用的最新3.2.4，@joostshao是不是你装了两个版本eigen，低版本/usr/include，高版本在/usr/include/local？

**Comment by joostshao** [comment]
/home/ubuntu/paracel/CMakeFiles/CMakeTmp/src.cxx:2:30: fatal error: eigen3/Eigen/Dense: 没有那个文件或目录

我两个都安装了 貌似

**Comment by mckelvin** [comment]
你的eigen3是用包管理工具装的吗？`apt-cache show libeigen3-dev`看看你发行版下eigen3的版本号。得确认是 eigen3 不是 eigen2。

```
root@595c94324b7a:/# apt-cache search eigen3
libeigen3-dev - lightweight C++ template library for linear algebra
libeigen3-doc - eigen3 API documentation

root@595c94324b7a:/# apt-cache show libeigen3-dev
Package: libeigen3-dev
Priority: extra
Section: universe/libdevel
Installed-Size: 3729
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
Architecture: all
Source: eigen3
Version: 3.2.0-8
Provides: libeigen2-dev
Depends: pkg-config
Suggests: libeigen3-doc, libmrpt-dev
Filename: pool/universe/e/eigen3/libeigen3-dev_3.2.0-8_all.deb
Size: 494158
MD5sum: d5f61139db08a1d4e2040161685e43d8
SHA1: eae74eb866634e639f092b32029307dc9258f55f
SHA256: 67194a20f0a59623a46923ca68b6dc35e5e9cdcad09fe882feb0c3e8988d7aec
Description: lightweight C++ template library for linear algebra
Description-md5: 71025bd67be9e83075fd5a0e7ab822a2
Homepage: http://eigen.tuxfamily.org
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 9m
```

**Comment by joostshao** [comment]
apt-cache show libeigen3-dev
Package: libeigen3-dev
Priority: extra
Section: universe/libdevel
Installed-Size: 3729
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
Architecture: all
Source: eigen3
Version: 3.2.0-8
Provides: libeigen2-dev
Depends: pkg-config
Suggests: libeigen3-doc, libmrpt-dev
Filename: pool/universe/e/eigen3/libeigen3-dev_3.2.0-8_all.deb
Size: 494158
MD5sum: d5f61139db08a1d4e2040161685e43d8
SHA1: eae74eb866634e639f092b32029307dc9258f55f
SHA256: 67194a20f0a59623a46923ca68b6dc35e5e9cdcad09fe882feb0c3e8988d7aec
Description-en: lightweight C++ template library for linear algebra
 Eigen 3 is a lightweight C++ template library for vector and matrix math,
 a.k.a. linear algebra.
 .
 Unlike most other linear algebra libraries, Eigen 3 focuses on the simple
 mathematical needs of applications: games and other OpenGL apps, spreadsheets
 and other office apps, etc. Eigen 3 is dedicated to providing optimal speed
 with GCC. A lot of improvements since 2-nd version of Eigen.
Description-md5: 71025bd67be9e83075fd5a0e7ab822a2
Homepage: http://eigen.tuxfamily.org
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 9m

一模一样 ,但是 也下载了手动编译 而且sudo make install 了

**Comment by joostshao** [comment]
现在可以了,我把原来的apt的卸载,就用手动编译的,现在可以了

**Comment by joostshao** [comment]
为毛编译那么慢?
