### ISSUE TITLE
str_split语义问题

### ISSUE THREAD

**Issue by kainwen** [douban/paracel#7]
在python中split如下：
```python
In [1]: s = "\tasd"
In [2]: s.split('\t')
Out[2]: ['', 'asd']
````

在paracel中str_split实现如下： https://github.com/douban/paracel/blob/master/include/utils/ext_utility.hpp#L36

```c++
string_lst str_split(const paracel::str_type & str, 
                     const char sep) {
  string_lst result;
  size_t st = 0, en = 0;
  while(1) {
    en = str.find(sep, st);
    auto s = str.substr(st, en - st);
    if(s.size()) result.push_back(std::move(s));
    if(en == paracel::str_type::npos) break;
    st = en + 1;
  }
  return result;
}
```

其中`if (s.size())` 这个判断会使得str_split行为和python的split不一样。造成的结果是，"a\tb"用split后得到的list长度可能会变化。

是否修改？

**Comment by xunzhang** [comment]
`paracel::str_split` is used for parsing internal arguments, which could be used for parsing input data as well. I don't think it's necessary to be the same with `python::split`.
