### ISSUE TITLE
Sparse data

### ISSUE THREAD

**Issue by pangolulu** [douban/paracel#8]
Hi, I am very interesting in this project. And I think the API is very friendly. I am wondering that how I can support very sparse data in paracel. Because in your lr code, the data format is just "feature_1,feature_2,...,feature_k". Thanks a lot.

**Comment by xunzhang** [comment]
@pangolulu You could use APIs like `paracel_load_as_graph`/`paracel_load_as_matrix` to create a graph/matrix representing sparse formats directly from input data. The document can be found [here](http://paracel.io/docs/api_reference.html#load) and you can also refer other application codes(in the `alg` folder) for sample usage such as matrix factorization.

**Comment by pangolulu** [comment]
@xunzhang OK, thanks. I will read more application codes.
